export const SHOW_PAGE = 'SHOW_PAGE';

export const FETCH_TEAMS = 'FETCH_TEAMS';
export const SELECT_TEAM = 'SELECT_TEAM';
export const ADD_MEMBER_TO_TEAM = 'ADD_MEMBER_TO_TEAM';

export const POST_BOARD = 'POST_BOARD';
export const FETCH_BOARD = 'FETCH_BOARD';
export const FETCH_ACTIVE_BOARDS = 'FETCH_ACTIVE_BOARDS';
export const FETCH_TEAM_ACTIVE_BOARDS = 'FETCH_TEAM_ACTIVE_BOARDS';
export const UPDATE_SELECTED_MEMBER = 'UPDATE_SELECTED_MEMBER';
