export const SHOW_PAGE = 'SHOW_PAGE';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const FETCH_TEAMS = 'FETCH_TEAMS';
export const SELECT_TEAM = 'SELECT_TEAM';
export const ADD_MEMBER_TO_TEAM = 'ADD_MEMBER_TO_TEAM';

export const POST_BOARD = 'POST_BOARD';
export const PATCH_BOARD = 'PATCH_BOARD';
export const FETCH_BOARD = 'FETCH_BOARD';
export const FETCH_ACTIVE_BOARDS = 'FETCH_ACTIVE_BOARDS';
export const FETCH_TEAM_ACTIVE_BOARDS = 'FETCH_TEAM_ACTIVE_BOARDS';
export const UPDATE_SELECTED_MEMBER = 'UPDATE_SELECTED_MEMBER';

export const PATCH_ITEM = 'PATCH_ITEM'
export const POST_ITEM = 'POST_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const POST_ACTION = 'POST_ACTION'
export const PATCH_ACTION = 'PATCH_ACTION'

export const SELECT_ITEM = 'SELECT_ITEM'

export const FETCH_USERS = 'FETCH_USERS'
