groups:
- name: Xetro
  jobs:
  - tests
  - backup-database
  - push-to-cf

jobs:
- name: tests
  serial: true
  plan:
  - in_parallel:
    - { get: xetro, trigger: true, passed: [] }
  - task: tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
      inputs:
      - name: xetro
      run:
        path: xetro/ci/tasks/run-tests.sh

- name: backup-database
  serial: true
  plan:
  - in_parallel:
    - { get: xetro, trigger: true, passed: [tests] }
  - task: backup-database
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
      inputs:
      - name: xetro
      run:
        path: xetro/ci/tasks/backup-database.sh
      params: &cf
        APP_NAME:                       xetro
        CF_DOMAIN:                      {{cf_domain}}
        CF_ENDPOINT:                    {{cf_endpoint}}
        CF_ORG:                         {{cf_org}}
        CF_SPACE:                       {{cf_space}}
        CF_USERNAME:                    {{cf_username}}
        CF_PASSWORD:                    {{cf_password}}
        CF_DB_SERVICE_NAME:             {{cf_db_service_name}}
        SSO_DELL_CLIENT_ID:             {{sso_dell_client_id}}
        SSO_DELL_CLIENT_SECRET:         {{sso_dell_client_secret}}
        SSO_DELL_AUTH_DOMAIN:           {{sso_dell_auth_domain}}
        SSO_DELL_USERINFO_URL:          {{sso_dell_userinfo_url}}
        DATABASE_BACKUP_HOST_SSH_KEY:   {{database_backup_host_ssh_key}}
        DATABASE_BACKUP_HOST_IP:        {{database_backup_host_ip}}
        DATABASE_BACKUP_HOST_USER:      {{database_backup_host_user}}
        DATABASE_BACKUP_MAX_DAYS:       7

- name: push-to-cf
  serial: true
  plan:
  - in_parallel:
    - get: xetro
      trigger: true
      passed: [backup-database]
  - task: push-to-cf
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
      inputs:
      - name: xetro
      run:
        path: xetro/ci/tasks/push-to-cf.sh
      params:
        <<: *cf

resources:
- name: xetro
  type: git
  icon: github
  source:
    uri: https://github.com/kaleo211/xetro
    branch: master
    private_key: {{xetro_private_key}}
    skip_ssl_verification: true
